# Generated by Django 5.0.7 on 2024-08-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('information', models.TextField()),
                ('image', models.ImageField(upload_to='personal/')),
                ('website', models.CharField(max_length=200)),
            ],
        ),
    ]
