# Generated by Django 5.0.7 on 2024-08-07 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_remove_educationinfo_image_educationinfo_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationinfo',
            name='video',
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='personal/'),
            preserve_default=False,
        ),
    ]
