# Generated by Django 5.0.7 on 2024-08-07 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_jobinfo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
