# Generated by Django 5.0.7 on 2024-08-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_profileinfo_github_profileinfo_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_body1',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_body2',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_body3',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_image1',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_image2',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_image3',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_title1',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_title2',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='sk_title3',
        ),
    ]
