# Generated by Django 5.0.7 on 2024-08-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0011_parttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttime',
            name='address',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='body',
            field=models.TextField(default='Fill the form'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='company',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='data',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='image',
            field=models.ImageField(default='Fill the form', upload_to='personal/'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='information',
            field=models.TextField(default='Fill the form'),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='title',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AlterField(
            model_name='parttime',
            name='website',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
    ]
