# Generated by Django 5.0.7 on 2024-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0012_alter_parttime_address_alter_parttime_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttime',
            name='addres1',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='addres2',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='body1',
            field=models.TextField(default='Fill the form'),
        ),
        migrations.AddField(
            model_name='parttime',
            name='body2',
            field=models.TextField(default='Fill the form'),
        ),
        migrations.AddField(
            model_name='parttime',
            name='company1',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='company2',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='data1',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='data2',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='image1',
            field=models.ImageField(default='Fill the form', upload_to='personal/'),
        ),
        migrations.AddField(
            model_name='parttime',
            name='image2',
            field=models.ImageField(default='Fill the form', upload_to='personal/'),
        ),
        migrations.AddField(
            model_name='parttime',
            name='information1',
            field=models.TextField(default='Fill the form'),
        ),
        migrations.AddField(
            model_name='parttime',
            name='information2',
            field=models.TextField(default='Fill the form'),
        ),
        migrations.AddField(
            model_name='parttime',
            name='title1',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='title2',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='website1',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
        migrations.AddField(
            model_name='parttime',
            name='website2',
            field=models.CharField(default='Fill the form', max_length=200),
        ),
    ]
